---
title: "MissionBio data quality Report"
output: 
  html_document: 
    df_print: kable
date: '2022-07-07'
---

```{r include=FALSE}

# load libraries
library(tidyverse)


#______ Ghob run _____
df <- data.table::fread("../data/h5_files_stats.tsv", skip = 1)[,-1]
df$proportion_mappedToCell_total_read_pairs <- df$n_read_pairs_mapped_to_cells %>% as.numeric() / df$n_read_pairs %>% as.numeric()
df$proportion_validCell_total_read_pairs <- df$n_read_pairs_valid_cell_barcodes %>% as.numeric() / df$n_read_pairs %>% as.numeric()
df$proportion_mappedInsert_total_reads <- df$n_reads_mapped_insert %>% as.numeric() / (df$n_read_pairs %>% as.numeric() *2)
df$proportion_bases_r1_q30 <- df$n_bases_r1_q30 %>% as.numeric() / df$n_bases_r1 %>% as.numeric()
df$proportion_bases_r2_q30 <- df$n_bases_r2_q30 %>% as.numeric() / df$n_bases_r2 %>% as.numeric()
df$proportion_bases_cellBarcode_q30 <- df$n_cell_barcode_bases_q30 %>% as.numeric() / df$n_cell_barcode_bases %>% as.numeric()

df$n_cell_barcode_bases_q30/1000000000
df$n_cell_barcode_bases/1000000000

df$dataset <- "Ghobrial_lab"
df$run <- "Ghob_run1"


melt <- reshape2::melt(df, id.vars="sample")


#______ bolo run1 _____
dfB1 <- data.table::fread("../data/h5_files_stats_RUN1.tsv", skip = 1)
dfB1$proportion_mappedToCell_total_read_pairs <- dfB1$n_read_pairs_mapped_to_cells %>% as.numeric() / dfB1$n_read_pairs %>% as.numeric()
dfB1$proportion_validCell_total_read_pairs <- dfB1$n_read_pairs_valid_cell_barcodes %>% as.numeric() / dfB1$n_read_pairs %>% as.numeric()
dfB1$proportion_mappedInsert_total_reads <- dfB1$n_reads_mapped_insert %>% as.numeric() / (dfB1$n_read_pairs %>% as.numeric() * 2)
dfB1$proportion_bases_r1_q30 <- dfB1$n_bases_r1_q30 %>% as.numeric() / dfB1$n_bases_r1 %>% as.numeric()
dfB1$proportion_bases_r2_q30 <- dfB1$n_bases_r2_q30 %>% as.numeric() / dfB1$n_bases_r2 %>% as.numeric()
dfB1$proportion_bases_cellBarcode_q30 <- dfB1$n_cell_barcode_bases_q30 %>% as.numeric() / dfB1$n_cell_barcode_bases %>% as.numeric()

dfB1$dataset <- "Bologna_lab"
dfB1$run <- "Bolo_run1"

meltB1 <- reshape2::melt(dfB1, id.vars="sample")



#______ bolo run2 _____
dfB2 <- xlsx::read.xlsx("../data/h5_files_stats.xlsx", sheetIndex = 1)
dfB2$proportion_mappedToCell_total_read_pairs <- dfB2$n_read_pairs_mapped_to_cells %>% as.numeric() / dfB2$n_read_pairs %>% as.numeric()
dfB2$proportion_validCell_total_read_pairs <- dfB2$n_read_pairs_valid_cell_barcodes %>% as.numeric() / dfB2$n_read_pairs %>% as.numeric()
dfB2$proportion_mappedInsert_total_reads <- dfB2$n_reads_mapped_insert %>% as.numeric() / (dfB2$n_read_pairs %>% as.numeric() * 2)
dfB2$proportion_bases_r1_q30 <- dfB2$n_bases_r1_q30 %>% as.numeric() / dfB2$n_bases_r1 %>% as.numeric()
dfB2$proportion_bases_r2_q30 <- dfB2$n_bases_r2_q30 %>% as.numeric() / dfB2$n_bases_r2 %>% as.numeric()
dfB2$proportion_bases_cellBarcode_q30 <- dfB2$n_cell_barcode_bases_q30 %>% as.numeric() / dfB2$n_cell_barcode_bases %>% as.numeric()

dfB2$dataset <- "Bologna_lab"
dfB2$run <- "Bolo_run2"

meltB2 <- reshape2::melt(dfB2, id.vars="sample")

allmelt <- rbind(melt, meltB1, meltB2)

interest_vars <- df %>% select_if(is.numeric) %>% names

allmelt$ID <- allmelt$sample %>% str_remove_all("scDNA_|_reference")
allmelt$ID <- allmelt$ID %>% factor(levels = str_sort(allmelt$ID %>% unique, numeric = T), ordered = T)


alldf <- rbind(df,dfB1, dfB2)

```

This report is aimed to obtain a global data quality analysis of scDNA-seq samples from MissionBio.

The total dataset includes:

-   6 samples from **Ghobrial's lab**: 5 cell lines samples + 1 mixture sample of the other 5 cell lines

-   16 samples from **Bologna's lab**: 16 PB samples from 2 separate sequencing runs (8+8)

------------------------------------------------------------------------

### All samples overview

```{r echo=FALSE}
alldf %>% select(sample, dataset, run, n_amplicons, chemistry_version, pipeline_version, n_cells, genome_version, ado_rate, avg_panel_uniformity)
```

number of cells

```{r echo=FALSE, fig.height=8, fig.width=10}
alldf %>% ggplot(aes(run, n_cells)) + 
  geom_violin(aes(fill=run), alpha= 0.3) +
  geom_boxplot(alpha=0.3)+
  geom_jitter(height = 0, width = 0.1) +
  stat_summary(geom="text", fun=quantile,
               aes(label=sprintf("%1.0f", ..y..), color=run),
               position=position_nudge(x=0.48), size=3) +
  ggtitle("number of cells per run")
```

```{r}

```

```{r}

```

```{r}

```
